--CREATE TABLE Employees (
	--Id INT PRIMARY KEY IDENTITY,
	--FirstName VARCHAR(40) NOT NULL,
	--LastName VARCHAR(40) NOT NULL,
	--DateOfBirth DATETIME2 NOT NULL
--);

-- INT FOREIGN KEY REFERENCES Table(Id)

CREATE TABLE BOOKS (
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(120),
	AuthorId INT FOREIGN KEY REFERENCES Author(Id),

);
DROP TABLE Author;